name: Feature Request
description: Request features to add to Weaver here.

labels: [enhancement]
body:
  - type: markdown
    attributes:
      label: What feature do you propose to be added to Weaver?
    validations:
      required: true
