name: Question
description: Have a question about Weaver? Send an issue asking for help and you should hopefully get a response.

labels: [question]
body:
  - type: markdown
    attributes:
      label: What's your question?
    validations:
      required: true
