[package]
name = "paracosm-daemon/weaver"
description = "Weaver is an alternative to the lightweight game framework Knit"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src"]

[dependencies]
