name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rokit
        uses: paracosm-daemon/setup-rokit-rblx@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: |
          selene ./src